### PR TITLE
Issue #490 one file input set to both job inputs not showing in recipe builder

### LINKED ISSUE #490: one file input set to both job inputs not showing in recipe builder
From #475 

Possible steps (using mock data built into UI):

Add job "constrained energy minimization" (a job that has two+ slots for inputs)
Add a file input (anything)
Back in the recipe, click the job node to open the modal
Add your file input to both slots of the input (same file input to each) -> both appear as desired
Close the modal
Click the job node again to open the modal -> only the first input slot has the file input, the other one is empty
This is at least one issue found. The recipe definition is built correctly (I can see that the recipe.definition.nodes.cem.input has both entries filled out with the file input), it just looks like a rendering issue in the modal.

### PR DESCRIPTION
**Pull request by Nikkala-AIS**
After modal close and reopen, both inputs now show in recipe builder,  even if it is the same input file for both. Close #490

### CODE REVIEW

**Comment by Rachel-ais** [comment]
This did fix the main issue the only other thing I didn't think of is that now if you remove the file input it removes it from both locations

**Comment by Nikkala-AIS** [comment]
I am working on a fix.

**Comment by Nikkala-AIS** [comment]
Removing one file input no longer removes both even if both are the same file.

**Comment by Nikkala-AIS** [comment]
Sure, I'll look at it on Alpha; it was working fine locally.

**Pull request merged**
