### PR TITLE
Issue 420 - Fix job timeline

### LINKED ISSUE #420: Fix job timeline
image

Looks fine locally but on Alpha it is unreadable

### PR DESCRIPTION
**Pull request by Rachel-ais**
I feel like this was too simple but it seems to work on Alpha 

fixes #420

### CODE REVIEW

**Comment by cshamis** [comment]
Can somebody shoot me some screenshots?

**Comment by Rachel-ais** [comment]
Its not the big timeline fix but the one on the Jobs details page. Here is what it was looking like on alpha vs with the fix. 

Before:
Screen Shot 2020-01-23 at 1 24 16 PM

After:
Screen Shot 2020-01-24 at 12 48 23 PM

**Comment by cshamis** [comment]
Rachel:

Would it be possible to add pre-step and post-step as different colors in
the "Executed" bar?
Also, not sure about usefulness of "created" it's could probably be dropped
right?

**Comment by Rachel-ais** [comment]
From a quick look I don't think the API stores those dates but I could be wrong. We can have a conversation about it with @emimaesmith if we feel it is something worth spending the time on.

**Pull request merged**
