### PR TITLE
Issue #89 - Required indication for form inputs

### LINKED ISSUE #89: Required indication for form inputs
Adding an * or other indication for form inputs that are required.

### PR DESCRIPTION
**Pull request by Rachel-ais**
fixes #89

### CODE REVIEW

**Comment by Rachel-ais** [comment]
So you want me to leave the text of the span blank?

**Comment by ericsvendsen-mil** [comment]
No, there won't be an additional span at all. Just this:
```
<span class="required">Title</span>
```
The whole label plus the asterisk will be red, but that's fine.

**Comment by Rachel-ais** [comment]
Ok I was concerned about the whole label being red

**Comment by ericsvendsen-mil** [comment]
If you'd rather just the asterisk be red, then all you have to do is move the `color` property to the `:after` definition:
```
.required {
    &:after {
        content: " *";
        color: var(--label-text-danger);
    }
}
```

**Pull request closed without merging**
